### ISSUE TITLE
Absent elementMetadata upon SimpleList creation

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#10]
This is probably related to the latest commit (bd2d4d3000f9c64c9025ddaa0afa8cd8c0c12646) but it seems that there are still some issues:

```r
library(S4Vectors)
X <- SimpleList(a=1)
mcols(X)
# NULL

Y <- SimpleList()
Y$a <- 1
mcols(Y)
# DataFrame with 1 row and 0 columns
```

I would have expected them to be the same. (To provide some context, the fact that they're not the same is causing `CHECK` failures for _SingleCellExperiment_.) Session information here:

```
R Under development (unstable) (2017-10-27 r73632)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] S4Vectors_0.17.36   BiocGenerics_0.25.3

loaded via a namespace (and not attached):
[1] compiler_3.5.0
```

**Comment by hpages** [comment]
Hi @LTLA, @lawremi, 

Commit https://github.com/Bioconductor/S4Vectors/commit/bd2d4d3000f9c64c9025ddaa0afa8cd8c0c12646 also breaks IRanges, GenomicRanges, and SummarizedExperiment unit tests:
- https://bioconductor.org/checkResults/3.7/bioc-LATEST/IRanges/
- https://bioconductor.org/checkResults/3.7/bioc-LATEST/GenomicRanges/
- https://bioconductor.org/checkResults/3.7/bioc-LATEST/SummarizedExperiment/

Michael, can you take a look at this? Most SimpleList derivatives need to have a NULL in their elementMetadata slot by default. Thanks!

H.

**Comment by lawremi** [comment]
At some point during the refactoring SimpleLists (at least) began having zero-row (and col) element metadata upon construction. I assumed you no longer wanted `NULL`, so I changed it to at least have the right number of rows.

**Comment by hpages** [comment]
Not sure what refactoring you're talking about. We had the `mcols` of most SimpleList derivatives set to NULL by default for years. Changing this seems to affect/break code/tests in several places so unless you're willing to deal with this, please don't make that change. Some SimpleList derivatives would still need to be exceptions though e.g. DataFrame, otherwise we would have infinite nesting of DataFrames. This is why the elementMetadata slot of the SimpleList class must be DataTable_OR_NULL:
```
> getSlots("SimpleList")
           listData         elementType     elementMetadata            metadata 
             "list"         "character" "DataTable_OR_NULL"              "list" 
```
Also it does not make much sense to do this for SimpleList but not for CompressedList derivatives.

**Comment by lawremi** [comment]
I'm talking about the refactoring that you did. I'm not saying that it caused it; that's just about when it started happening. I'm totally happy with leaving it defaulting to `NULL` and was surprised that it was no longer that way.

**Comment by hpages** [comment]
I did many refactoring of many things in many places at many times ;-) so I still don't know what refactoring exactly you're talking about. I also don't know what "started happening". If you're talking about my recent refactoring of the IntegerRanges and GenomicRanges class hierarchies (which is still a work-in-progress), I don't remember having changed things related to the `mcols` of SimpleList objects during this particular refactoring. It could be that I did, in which case it was not intentional. It would help if you could be more specific.

**Comment by lawremi** [comment]
I can't reproduce the issue I was having (it was causing a failure in HelloRanges), so I just reverted the change.

**Comment by hpages** [comment]
Thanks!

**Comment by lawremi** [comment]
Well I have finally reproduced the problem. It's specifically GenomicRangesList that changed behavior, and thus `S4Vectors:::new_SimpleList_from_list()` is broken, because it breaks encapsulation by calling `new()`. I was thinking it could figure out a constructor to call instead. But that still makes assumptions, because constructors do not necessarily construct objects that are instances of the class of the same name. `GenomicRangesList()` is a good example, as it creates a SimpleGenomicRangesList object. Some workarounds are possible, but nothing clean.

One compromise is to continue calling `new()` but specially handle `@elementMetadata`. If the prototype has a DataFrame instead of `NULL`, create a zero-col DataFrame with the right number of rows. That's what I've done since it's a simple solution.

**Comment by hpages** [comment]
As a heads up, `GenomicRangesList()` will go away at some point (when the `GRangesList()` constructor gets the `compress` argument), the same way that `RangeList()` went away already.

**Comment by lawremi** [comment]
Ok. Originally GenomicRangesList was meant to be just a list of GenomicRanges objects. GRangesList have a special semantic of being "compound ranges", while I often just have one GenomicRanges per sample, condition, etc. I guess your plan is to remove that distinction.
