### ISSUE TITLE
call `rbind` instead of `c` for mono-dimensional array

### ISSUE THREAD

**Issue by Liubuntu** [Bioconductor/S4Vectors#11]
Hi, 

inside `rbind` method of `DataFrame`, when we do the combining of each column, it called `c` function if `!rectangular`. However, if we have a 1-dimension array inside the `DataFrame` object, the returned column will lose the attribute of `array`. 

```
a <- array(1:20, 20)
df <- DataFrame(a)
df
DataFrame with 20 rows and 1 column
          a
    <array>
1         1
2         2
3         3
4         4
5         5
...     ...
16       16
17       17
18       18
19       19
20       20
df1 <- rbind(df, df)
df1
DataFrame with 40 rows and 1 column
            a
    <integer>
1           1
2           2
3           3
4           4
5           5
...       ...
36         16
37         17
38         18
39         19
40         20
is.array(df[[1]])
[1] TRUE
dim(df[[1]])
[1] 20
is.array(df1[[1]])
[1] FALSE
```
We do want this to work because the `DataFrame` could accommodate different data types, including `DelayedArray`. We want the columns to be remained `DelayedArray` after `rbind`. 

```
 > a <- array(1:20, 20)                                                                                                                                                                                            
 > ad <- DelayedArray(a)                                                                                                                                                                                           
 > df1 <- DataFrame(letters=letters[1:20], ad=I(ad))                                                                                                                                                               
 > rbind(df1, df1)                                                                                                                                                                                                 
 DataFrame with 40 rows and 2 columns
         letters        ad
     <character> <integer>
 1             a         1
 2             b         2
 3             c         3
 4             d         4
 5             e         5
 ...         ...       ...
 36            p        16
 37            q        17
 38            r        18
 39            s        19
 40            t        20
```
Although in `DelayedArray` package, we may want the `rbind` method to work for not only `DelayedMatrix` which is exactly 2-dimensional, but also mono-dimensional (and higher-dimensional). This seems has already been achieved by the function of `DelayedArray::arbind`. Maybe a simple rename of `arbind` to be `rbind` would be good enough? There might be other issues though and I am not so sure of it. @hpages , Thanks!

Best,
Qian

**Comment by mtmorgan** [comment]
@lawremi do you have any comments on this?

**Comment by lawremi** [comment]
Just an initial comment: this is something that should be fixed. The `arbind()` function depends on IRanges and stuff so it's probably not directly portable. But I have started writing up a simple substitute.

**Comment by lawremi** [comment]
I think we should move the `arbind()` generic up to S4Vectors, so that `rbind,DataFrame()` can call that on non-matrices. The `simple_abind()` function is probably a lot faster and safer than my functions, but it's also a lot more complicated (despite its name) and depends on IRanges. I'll leave this stuff here in case it is useful to @hpages, who is probably the best qualified to integrate this. One thing this supports that `rbind()` and `arbind()` do not is carrying over the names on the dimnames. A rarely used feature, but still used.
```
find_other_dimnames <- function(dns) {
    lapply(seq_along(dns[[1L]])[-1L], function(d) {
        Find(Negate(is.null), lapply(dns, `[[`, d))
    })
}

rbind_dimnames <- function(arrays) {
    dns <- lapply(arrays, dimnames)
    rownames <- unlist(lapply(dns, `[[`, 1L))
    dimnames <- c(list(rownames), find_other_dimnames(dns))
    if (all(vapply(dimnames, is.null, logical(1L))))
        return(NULL)
    names(dimnames) <- names(dimnames(arrays[[1L]]))
    dimnames
}

rbind_dim <- function(arrays) {
    ndim <- length(dim(arrays[[1L]]))
    dims <- vapply(arrays, dim, integer(ndim))
    c(sum(dims[1L,]), dim(arrays[[1L]])[-1L])
}

rbind_as_matrix <- function(arrays) {
    other_dim <- dim(arrays[[1L]])[-1L]
    toMatrix <- function(m) {
        this_other_dim <- dim(m)[-1L]
        if (!identical(other_dim, this_other_dim)) {
            return("the objects to bind have incompatible dimensions")
        }
        dim(m) <- c(nrow(m), prod(this_other_dim))
        m
    }
    matrices <- lapply(arrays, toMatrix)
    do.call(rbind, matrices)
}

array_rbind <- function(arrays) {
    matrix <- rbind_as_matrix(arrays)
    dim <- rbind_dim(arrays)
    dimnames <- rbind_dimnames(arrays)
    array(matrix, dim, dimnames)
}

rows_to_cols <- function(a) {
    aperm(a, c(2L, 1L, tail(dim(a), -2L))) 
}

array_cbind <- function(arrays) {
    rows_to_cols(array_rbind(lapply(arrays, rows_to_cols)))
}
```

**Comment by hpages** [comment]
The `rbind` method for DataFrame objects should probably use `concatenateObjects()` internally to combine columns. `concatenateObjects()` provides the "bind along the ROWS" semantic that `rbind` expects i.e. it acts like `c()` on vector-like objects and like `rbind()` on array-like objects (even though it doesn't do the right thing on DataFrame objects at the moment so that needs to be fixed too). This will address the issue we're observing now when rbind'ing 2 DataFrames that have columns that are 1D array-like objects (the `dim` attribute gets dropped when it should not).

BTW maybe I should have named this low-level generic `bindROWS()` instead of `concatenateObjects()` to reflect the "bind along the ROWS" semantic. This name would also make it easier to associate with the `extractROWS` low-level generic which it complements.

I will make these changes.

**Comment by hpages** [comment]
This is done in S4Vectors 0.19.5: 1664d3f14e811324d462f25ced935a90764b7758

I also added a `bindROWS` method for DelayedArray objects (https://github.com/Bioconductor/DelayedArray/commit/63545d8a6e2143db5abd9a4126f3ed18f1cdebab) so `rbind()` now should work properly on DataFrame objects that contain DelayedArray objects with an arbitrary number of dimensions, including 1D objects.

**Comment by Liubuntu** [comment]
These enhancements for `DelayedArray` and `S4Vectors` are awesome! Thanks @hpages !
