### ISSUE TITLE
indexed subassignment fails

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/S4Vectors#117]
Hi Hervé, @hpages 

This seems to have worked previously but there may have been a change to `DataFrame`. Do you think this is the case? Is the replacement more strict, meaning the name of the variables should be provided in the left-hand side? 

``` r
suppressPackageStartupMessages(library(S4Vectors))
a <- DataFrame(row.names = letters[1:3])
a[1:3, ] <- DataFrame(score = 1:3)
#> Error in .subassign_columns(x, nsbs, value): provided 1 variables to replace 0 variables
```

<sup>Created on 2023-08-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

FWIW, the following works though it is a bit redundant:

```r
a[1:3, "score"] <- DataFrame(score = 1:3)
```

-Marcel

**Comment by hpages** [comment]
Hi Marcel,

I don't think this has ever worked. I get the same "provided 1 variables to replace 0 variables" error in BioC 3.18, 3.17, and 3.16.

Note that your example above fails for the same reason as this fails:
```
DF <- DataFrame(A=11:13)
DF[1:3, ] <- DataFrame(score=1:3, score2=21:23)
# Error in .subassign_columns(x, nsbs, value) : 
#   provided 2 variables to replace 1 variables
```
IMO the error message accurately describes the problem.

FWIW trying to do the same with an ordinary data.frame doesn't do what you seem to expect either.

So it's not really clear to me that we should make this work. 

Finally note that the operation you're trying to perform can also be done with:
```
cbind(a, DataFrame(score = 1:3))
```
This is not redundant and is more readable IMO since it makes it very clear what the operation is about.

H.

**Comment by hpages** [comment]
See https://github.com/Bioconductor/RaggedExperiment/issues/29 for a follow up on this.
