### ISSUE TITLE
cbinding DataFrames does not preserve metadata?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/S4Vectors#12]
Pretty much as the title says. I would have expected that the metadata of the first `DataFrame` would be present in the output. Is this an oversight or intended behaviour?

```r
library(S4Vectors)
X <- DataFrame(x=1)
metadata(X)$whee <- 2
metadata(X) # so far so good
## $whee
## [1] 2

metadata(cbind(X, X))
## list()
```

Also, `?"cbind,DataFrame-method"` seems to suggest that row names are dropped in `cbind`. I assume that this is not the intended message, as row names seem be preserved:

```r
X <- DataFrame(x=1, row.names="A")
rownames(cbind(X, X))
## [1] "A"
```

Running on _S4Vectors_ version 0.17.39.

**Comment by lawremi** [comment]
I'm pretty sure it was intended, since `cbind()` is just constructing a new DataFrame, almost symmetrically but not quite, because rownames are taken from the first argument that has them. Subassignment of the second into the first should make the intent more obvious, but I realize that's not as convenient. And now we have examples like `c,Vector()` that takes the metadata from the first element. So I'll change `cbind()` and `rbind()` to behave that way, too.

Thanks for pointing out the out of date documentation. I cleaned that up. That stuff was ancient.
