### ISSUE TITLE
S4Vectors::rename() conflicts with dplyr::rename()

### ISSUE THREAD

**Issue by Jacob-E-Munro** [Bioconductor/S4Vectors#5]

**Comment by hpages** [comment]
`S4Vectors::rename()` and `dplyr::rename()` are just 2 different generic functions with unfortunately different signatures and semantics so it doesn't seem that it would be desirable to merge them into a single generic. The fact that one will mask the other one is a (known) annoyance that you can work around by using `S4Vectors::rename()` or `dplyr::rename()` instead of just `rename()`. Note that this is not an S4Vectors issue more than a dplyr issue.

For the record Michael (@lawremi) added the `rename()` generic to IRanges in Dec 2011 and the generic was then moved to S4Vectors in April 2014. I don't know if this is used and by who. I'll let Michael decide if he wants to keep this in S4Vectors. In any case, given what it does, it's probably something that should belong to base R rather than S4Vectors.

**Comment by lawremi** [comment]
I'm sure a lot of code uses it by now. The syntax is unfortunately the opposite of the `dplyr::rename()`, which can be confusing. If anything went into base R it would be more like the dplyr version.

**Comment by Jacob-E-Munro** [comment]
Thanks for the responses. I guess I was hoping it would straightforward enough to merge them into a single generic, but I see your point about the different semantics.

**Comment by hpages** [comment]
Here are the numbers for the record: of the dozens of Bioconductor packages that use `rename()`, only the 5 following packages use `S4Vectors::rename()`: `mygene`, `FindMyFriends`, `MAST`, `TnT`, `gmapR`. All the other ones use `dplyr::rename()` or `plyr::rename()` or `reshape::rename()`. Kind of surprisingly `plyr::rename()` and `reshape::rename()` have the same semantic as `S4Vectors::rename()`.

**Comment by lawremi** [comment]
That's interesting. It is of course important to keep in mind that there is a lot more code in the wild, and that renaming would be common in analysis scripts.
