### ISSUE TITLE
DataFrames are being converted to DFrames

### ISSUE THREAD

**Issue by jgranja24** [Bioconductor/S4Vectors#66]
To whom it may concern,

I am currently having issues where i am saving and RDS of a "DataFrame" and now when i load it on a different console with slightly different R versions (ive tested 3 different machines) they all now have errors because they are not seen as DataFrames

saved as 

DataFrame with 50 rows and 1 column
                                         ArrowFiles
                                        <character>
01_999_CD4Mem_CD8Naive 01_999_CD4Mem_CD8Naive.arrow
01_999_Mono_T                   01_999_Mono_T.arrow
05_995_CD4Mem_CD8Naive 05_995_CD4Mem_CD8Naive.arrow
05_995_Mono_T                   05_995_Mono_T.arrow
10k_pbmc                             10k_pbmc.arrow
...                                             ...

read in as

An object of class "DFrame"
<S4 Type Object>

attr(,"rownames")
 [1] "01_999_CD4Mem_CD8Naive"  "01_999_Mono_T"          
 [3] "05_995_CD4Mem_CD8Naive"  "05_995_Mono_T"          
 [5] "10k_pbmc"                "1_99_CD4Mem_CD8Naive"   ...

attr(,"nrows")
[1] 50
attr(,"listData")
attr(,"listData")$ArrowFiles
 [1] "01_999_CD4Mem_CD8Naive.arrow"  "01_999_Mono_T.arrow"          
 [3] "05_995_CD4Mem_CD8Naive.arrow"  "05_995_Mono_T.arrow"   ...

attr(,"elementType")
[1] "ANY"
attr(,"elementMetadata")
`\001NULL\001`
attr(,"metadata")
list()

Which i get the saving session info is ahead but this is an extreme problem as I have written a custom package that now does not have backwards compatibility because of this.

session info of saving
 [1] gridExtra_2.3               ggrastr_0.1.7              
 [3] customPackage_0.1                magrittr_1.5               
 [5] rhdf5_2.30.1                Matrix_1.2-17              
 [7] data.table_1.12.8           SummarizedExperiment_1.16.1
 [9] DelayedArray_0.12.2         BiocParallel_1.20.1        
[11] matrixStats_0.55.0          Biobase_2.46.0             
[13] GenomicRanges_1.38.0        GenomeInfoDb_1.22.0        
[15] IRanges_2.20.2              S4Vectors_0.24.3           
[17] BiocGenerics_0.32.0         ggplot2_3.2.1  

session info of reading attempt 1
 [1] customPackage_0.1     magrittr_1.5               
 [3] rhdf5_2.26.2                Matrix_1.2-15              
 [5] data.table_1.12.8           SummarizedExperiment_1.12.0
 [7] DelayedArray_0.8.0          BiocParallel_1.16.6        
 [9] matrixStats_0.55.0          Biobase_2.42.0             
[11] GenomicRanges_1.34.0        GenomeInfoDb_1.18.2        
[13] IRanges_2.16.0              S4Vectors_0.20.1           
[15] BiocGenerics_0.28.0         ggplot2_3.2.1  

session info of reading attempt 2
[1] customPackage_0.1         magrittr_1.5        
 [3] rhdf5_2.28.1        Matrix_1.2-18        
 [5] data.table_1.12.8      SummarizedExperiment_1.14.1
 [7] DelayedArray_0.10.0     BiocParallel_1.18.1     
 [9] matrixStats_0.55.0     Biobase_2.44.0       
[11] GenomicRanges_1.36.1    GenomeInfoDb_1.20.0     
[13] IRanges_2.18.3       S4Vectors_0.22.1      
[15] BiocGenerics_0.30.0     ggplot2_3.2.1

**Comment by hpages** [comment]
You're not saying what error you are getting. Also you're not showing the `sessionInfo()` you're getting in the session where you're loading the serialized object.

So here is the situation: Starting with Bioconductor 3.10, the `DataFrame()` constructor returns an object of class DFrame. This is expected. These objects won't work with older versions of Bioconductor. This is also expected.

Generally speaking it's not reasonable to expect that S4 objects created with a given version of Bioconductor will work with **earlier** versions of Bioconductor. To make a blunt analogy this would be like trying to use a version of Microsoft Office from the 90's to open a document created with Microsoft Office 2019. Guess what's going to happen? Or to try to read a blu-ray disc with a traditional DVD player.

Only the opposite is a reasonable expectation e.g. documents created with an old version of MS Office should be compatible with more recent versions of MS Office, most blu-ray players should be able to play traditional DVD's, etc... So we're doing our best to make sure that future versions of Bioconductor will remain compatible with old serialized DataFrame objects but that's all we can do.

Hope that makes sense,
H.

**Comment by hpages** [comment]
> this is an extreme problem as I have written a custom package that now does not have backwards compatibility because of this

Also can you expand on that? We have 1800+ software packages in Bioconductor and after the  `DataFrame()` constructor was modified to return a DFrame instance instead of a DataFrame instance, only a dozen of them broke and needed some very minor adjustments to work again. Most of the time they broke because they were using things like `if (class(x) != "DataFrame")` instead of `if (!is(x, "DataFrame"))` i.e. they got what they deserved ;-)

H.

**Comment by jgranja24** [comment]
I see your point its just difficult if you cant convert back the basic elements. 
I just added a backwards function to convert the main components in case this occurs. Itd be useful to have something that goes:

as(object of class "DFrame", "DataFrame") and it backwards converts the main components.

Best

> Also can you expand on that? We have 1800+ software packages in Bioconductor and after the DataFrame() constructor was modified to return a DFrame instance instead of a DataFrame instance, only a dozen of them broke and needed some very minor adjustments to work again. Most of the time they broke because they were using things like if (class(x) != "DataFrame") instead of if (!is(x, "DataFrame")) i.e. they got what they deserved

Its more so the class ive been working with now reports:
$ operator not defined for this S4 class

Because the underlying class is not recognized anymore :

setClass("customProject", 
  representation(
    projectMetadata = "SimpleList",
    projectSummary = "SimpleList",
    sampleColData = "DataFrame",
    sampleMetadata = "SimpleList",
    cellColData = "DataFrame", 
    cellMetadata = "SimpleList", 
    reducedDims = "SimpleList",
    embeddings = "SimpleList",
    peakSet = "GRangesOrNull",
    peakAnnotation = "SimpleList",
    geneAnnotation = "SimpleList",
    genomeAnnotation = "SimpleList",
    imputeWeights = "SimpleList"
  )
)

Jeff

**Comment by hpages** [comment]
> as(object of class "DFrame", "DataFrame") and it backwards converts the main components.

Not a good idea because:

1. There should be no need to turn a DFrame instance into a DataFrame instance since a DFrame object `x` _is_ already a DataFrame object. "is" in the sense that `is(x, "DataFrame")` returns `TRUE` when `class(x)` is equal to DFrame. This means that DFrame objects work everywhere a DataFrame is expected. Except for code that uses things like `class(x) == "DataFrame"` (when they should really use `is(x, "DataFrame")`). In particular this means that the `sampleColData` slot of your customProject objects will accept a DFrame object (it expects a DataFrame object **or derivative** which is what a DFrame object is).

2. We actually want to go the other way around. The long-term goal is to have old serialized DataFrame instance slowly disappear and be replaced with DFrame instance.

3. And the reason they all need to disappear is because we want to turn DataFrame into a _virtual_ class in the future. This will allow the implementation of alternate DataFrame representations e.g. on-disk DataFrame objects (DFrame being the canonical in-memory representation).

I'd be happy to provide guidance if you need help adapting your code to make it work with DFrame objects (I fixed the dozens of Bioconductor packages that the switch from DataFrame to DFrame broke, and, as I said earlier, the fix is generally starightforward) but I would need more details about what's going wrong exactly. All you gave me is some vague statement about "$ operator not defined for this S4 class", but without more context and/or a reproducible example there is not much I can do.

H.

**Comment by jgranja24** [comment]
I see i think everything is fine, I have no concerns about forward compatibility. I just added the ability to go backwards for my use case if someone is in a situation where they dont want to update everything to access something from the data structure. 

An example would be I imagine if one saved a SummarizedExperiment and transferred it to a colleague who is on a previous version of R. That would not be read correctly even though the main components of an SE have not changed. To access basic functionality of that SE the person would need a simple converter of the attribute list to a DataFrame class.

> All you gave me is some vague statement about "$ operator not defined for this S4 class", but without more context and/or a reproducible example there is not much I can do.

This is just the error from above since the DFrame is not recognized its just a list of attributes when going backwards. I think everything is fine, thanks for the help.
