### ISSUE TITLE
object not found when evaluating evalSeparately

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/S4Vectors#80]
Cross-posting from https://github.com/kevinrue/TVTB/issues/8#issuecomment-819203340

I will investigate myself from the perspective of the package https://bioconductor.org/packages/release/bioc/html/TVTB.html , but in the meantime, I'd appreciate any feedback whether it should be expected that objects defined in the session global environment are not defined when `evalSeparately` is evaluated.

Thanks!

**Comment by hpages** [comment]
Hi Kevin,

The title of the issue is very cryptic. Can you tell us what objects you are talking about and maybe provide more context? A minimal self-contained reproducible example would be great.

Thanks,
H.

**Comment by kevinrue** [comment]
Hi Herve.

Thanks for the quick reply.

I linked to the original post in my opening comment, but I will paste the example below again.
Also, I have renamed this issue to something that is hopefully clearer and more generic.

### Code

```
all_filters <- c("ASSEMBLY_BIAS", "ASSEMBLY_ONLY", "PASS", "PON")
customFilterRules <- VcfFixedRules(
  exprs = list(
    all = expression(FILTER %in% all_filters)
))
> summary(evalSeparately(customFilterRules, gripss.var))
```

### Error

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': error in evaluating the argument 'args' in selecting a method for function 'do.call': Filter 'all' failed: object 'all_filters' not found
```

**Comment by lawremi** [comment]
In order to find symbols outside of the object being filtered (`gripss.var`), it is necessary to pass the containing environment via the `enclos=` argument. `evalSeparately()` cannot find the calling environment automatically (in general) because of nesting introduced by the methods package. We can hack around this via the promise in cases like `subset()`, and I guess in this specific case also, but it wouldn't work in general. It's typically easiest to just pass a closure instead of an expression for this reason.

**Comment by kevinrue** [comment]
This explanation is good enough for me to solve the original issue reported by the user. 
I'm happy to let you decide whether to close this issue here or keep it open until you "hack around via the promise".

Thanks!

**Comment by lawremi** [comment]
Hoping to fix this via the new R7 system (yea, that will be a while).
